// global

// Authentication
export const PULL_SESSION_INFO_REQUEST = 'PULL_SESSION_INFO_REQUEST'
export const SESSION_INFO_PULLED = 'SESSION_INFO_PULLED'
export const SESSION_INFO_FAILURE = 'SESSION_INFO_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Auctions
export const PULL_CURRENT_OPT_IN_REQUEST = 'PULL_CURRENT_OPT_IN_REQUEST'
export const PULL_CURRENT_OPT_IN_SUCCESS = 'PULL_CURRENT_OPT_IN_SUCCESS'
export const PULL_CURRENT_OPT_IN_FAILURE = 'PULL_CURRENT_OPT_IN_FAILURE'
export const PLACE_BID_REQUEST = 'PLACE_BID_REQUEST'
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS'
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE'
export const REGISTER_FOR_AUCTION_REQUEST = 'REGISTER_FOR_AUCTION_REQUEST'
export const REGISTER_FOR_AUCTION_SUCCESS = 'REGISTER_FOR_AUCTION_SUCCESS'
export const REGISTER_FOR_AUCTION_FAILURE = 'REGISTER_FOR_AUCTION_FAILURE'

// Auction rooms
export const AUCTION_ROOM_INFO_REQUEST = 'AUCTION_ROOM_INFO_REQUEST'
export const AUCTION_ROOM_INFO_SUCCESS = 'AUCTION_ROOM_INFO_SUCCESS'
export const AUCTION_ROOM_INFO_FAILURE = 'AUCTION_ROOM_INFO_FAILURE'
export const AUCTION_ROOM_CONCISE_INFO_REQUEST = 'AUCTION_ROOM_CONCISE_INFO_REQUEST'
export const AUCTION_ROOM_CONCISE_INFO_SUCCESS = 'AUCTION_ROOM_CONCISE_INFO_SUCCESS'
export const AUCTION_ROOM_CONCISE_INFO_FAILURE = 'AUCTION_ROOM_CONCISE_INFO_FAILURE'
export const CHECK_FOR_RUNNING_AUCTION_REQUEST = 'CHECK_FOR_RUNNING_AUCTION_REQUEST'
export const CHECK_FOR_RUNNING_AUCTION_SUCCESS = 'CHECK_FOR_RUNNING_AUCTION_SUCCESS'
export const CHECK_FOR_RUNNING_AUCTION_FAILURE = 'CHECK_FOR_RUNNING_AUCTION_FAILURE'

// /////////////////////////////////////////////////////////
// ///////////////// Administration ////////////////////////
// /////////////////////////////////////////////////////////

// Products
export const PULL_PRODUCTS_REQUEST = 'PULL_PRODUCTS_REQUEST'
export const PULL_PRODUCTS_COMPLETE = 'PULL_PRODUCTS_COMPLETE'
export const PULL_PRODUCTS_FAILURE = 'PULL_PRODUCTS_FAILURE'
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'
export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE'
export const PRODUCT_SAVED_RESET = 'PRODUCT_SAVED_RESET'
export const DESTROY_PRODUCT_REQUEST = 'DESTROY_PRODUCT_REQUEST'
export const DESTROY_PRODUCT_SUCCESS = 'DESTROY_PRODUCT_SUCCESS'
export const DESTROY_PRODUCT_FAILURE = 'DESTROY_PRODUCT_FAILURE'
